[package]
name = "ollamars"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.23", features = ["blocking", "json", "cookies"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }